
spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native: 
                    search-locations: file:///C:/Microservices-Spring/microservices/configs,file:///C:/Microservices-Spring/microservices/configs/{application}
                
server:
    port: 8888